Proiect.WebApp/Controllers/ContactController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Proiect.WebApp.Controllers
{
    public class ContactController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

Proiect.WebApp/Controllers/LoginController.cs
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Mvc;
using Proiect.BusinessLogic;
using Proiect.Common;
using Proiect.Entities;
using Proiect.WebApp.Models.Account;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;

namespace Proiect.WebApp.Controllers
{
    public class LoginController : Controller
    {
        private readonly UserAccountService accountService;
        public LoginController(UserAccountService accountService)
        {
            this.accountService = accountService;
        }

        [HttpGet]
        public IActionResult Index()
        {
            var model = new LoginViewModel();
            model.IsPacient = bool.TrueString;
            model.IsAdmin = false;
            model.IsValid = true;
            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Index(LoginViewModel model)
        {
            if (ModelState.IsValid)
            {
                if (bool.Parse(model.IsPacient))
                {
                    var pacient = accountService.LoginPatient(model.Email);
                    if (pacient == null)
                    {
                        model.IsValid = false;
                        return View(model);
                    }
                    else
                    {
                        var canLogin = BCrypt.Net.BCrypt.Verify(model.Password, pacient.Person.Password);
                        if (canLogin)
                        {
                            var user = pacient.Person;
                            await LogIn(user, "Patient");
                            model.Password = null;
                            return RedirectToAction("Index", "Patient", new { idPerson = user.Id });
                        }
                        else
                        {
                            model.IsValid = false;
                            return View(model);
                        }
                    }
                }
                else
                {
                    var medic = accountService.LoginMedic(model.Email);                   
                    if (medic == null)
                    {
                        model.IsValid = false;
                        return View(model);
                    }
                    else
                    {
                        var canLogin = BCrypt.Net.BCrypt.Verify(model.Password, medic.Person.Password);
                        if (canLogin)
                        {
                            var user = medic.Person;
                            if (user.IsAdmin)
                            {
                                model.IsAdmin = user.IsAdmin;
                            }
                            await LogIn(user, "Medic");
                            model.Password = null;
                            return RedirectToAction("Index", "Medic", new { idPerson = user.Id });
                        }
                        else
                        {
                            model.IsValid = false;
                            return View(model);
                        }
                    }
                }
            }
            return View(model);
        }

        private async Task LogIn(Person user, string rol)
        {
            var claims = new List<Claim>
            {
                new Claim("Id", user.Id.ToString()),
                new Claim(ClaimTypes.Name, $"{user.LastName} {user.FirstName}"),
                new Claim(ClaimTypes.Email, user.Email),
                new Claim(ClaimTypes.Role,rol),
                new Claim(ClaimTypes.Surname,user.IsAdmin.ToString())
            };

            var identity = new ClaimsIdentity(claims, "Cookies");
            var principal = new ClaimsPrincipal(identity);

            await HttpContext.SignInAsync(
                    scheme: "ProiectCookies",
                    principal: principal);
        }

        public async Task<IActionResult> Logout()
        {
            await LogOut();

            return RedirectToAction("Index", "Home");
        }

        private async Task LogOut()
        {
            await HttpContext.SignOutAsync(scheme: "ProiectCookies");
        }
    }
}

Proiect.WebApp/Controllers/RegisterController.cs
using AutoMapper;
using Microsoft.AspNetCore.Mvc;
using Proiect.BusinessLogic;
using Proiect.Entities;
using Proiect.WebApp.Models.Account;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Proiect.WebApp.Controllers
{
    public class RegisterController : Controller
    {
        private readonly UserAccountService service;
        private readonly IMapper mapper;
        public RegisterController(UserAccountService service,
            IMapper mapper)
        {
            this.service = service;
            this.mapper = mapper;
        }
        [HttpGet]
        public IActionResult Index()
        {
            var model = new RegisterViewModel();
            model.IsPacient = bool.TrueString;
            return View(model);
        }

        [HttpPost]
        public IActionResult Index(RegisterViewModel model)
        {
            if (ModelState.IsValid)
            {
                var user = mapper.Map<Person>(model);
                user.Password = BCrypt.Net.BCrypt.HashPassword(user.Password);

                if (service.CanRegister(user) == false)
                {
                    return View(model);
                }

                string tabela = "";
                if (bool.Parse(model.IsPacient))
                {
                    tabela = "Patient";
                }
                else
                {
                    tabela = "Medic";
                }
                service.RegisterNewUser(user, tabela);
                return RedirectToAction("Index", "Home");
            }
            return View(model);
        }
    }
}

Proiect.WebApp/Views/Shared/ErrorPage.cshtml
<div class="mt-3 p-2 alert-danger text-center">
    <h2 class="text-danger">Ne pare rău, a apărut o eroare!</h2>
</div>

Proiect.WebApp/Views/Shared/NoAccessPage.cshtml
<div class="mt-3 p-2 alert-info text-center">
    <h2>NU AVEȚI ACCES LA ACEASTĂ PAGINĂ!</h2>
</div>

Proiect.WebApp/Views/Shared/_Carousel.cshtml
@inject LoginViewModel UserLogIn

<div id="myCarousel" class="carousel carousel-fade" data-ride="carousel">
    <ol class="carousel-indicators">
        <li data-target="myCarousel" data-slide-to="0" class="active"></li>
        <li data-target="myCarousel" data-slide-to="1"></li>
        <li data-target="myCarousel" data-slide-to="2"></li>
        @if (!UserLogIn.IsLogedIn)
        {<li data-target="myCarousel" data-slide-to="3"></li>}
    </ol>
    <div class="carousel-inner">
        <div class="carousel-item active" data-interval="5000">
            <img class="overlay-image" src="~/images/medic.jpg" />
            <div class="carousel-caption d-none d-md-block">
                <h5>Programarea unei consultații la un click distanță</h5>
                <p>Aplicația oferă posibilitatea de a cere o consultație medicală unui medic specialist direct din cadrul platformei.</p>
            </div>
        </div>
        <div class="carousel-item" data-interval="5000">
            <img class="overlay-image" src="~/images/medicine.jpg" />
            <div class="carousel-caption d-none d-md-block">
                <h5>Înregistrează-ți medicația</h5>
                <p>Prin intermediul aplicației îți poți înregistra medicamentele administrate zilnic.</p>
            </div>
        </div>
        <div class="carousel-item" data-interval="5000">
            <img class="overlay-image" src="~/images/stethoscope.jpg" />
            <div class="carousel-caption">
                <h5>Cere sfatul unui medic</h5>
                <p>Poți apela la un medic pentru interpretarea analizelor sau pentru a cere o a doua opinie medicală.</p>
            </div>
        </div>
        @if (!UserLogIn.IsLogedIn)
        {
            <div class="carousel-item" data-interval="5000">
            <img src="~/images/register.jpg" class="overlay-image" />
            <div class="carousel-caption d-none d-md-block">
                <h5>Încearcă acum!</h5>
                <div class="div-buttons">
                    <a asp-controller="Login" asp-action="Index" class="btn btn-info">Autentificare</a>
                    <a asp-controller="Register" asp-action="Index" class="btn btn-info">Înregistrare</a>
                </div>
            </div>
        </div>
        }
    </div>
    <a href="#myCarousel" class="carousel-control-prev" role="button" data-slide="prev">
        <span class="sr-only">Previous</span>
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    </a>
    <a href="#myCarousel" class="carousel-control-next" role="button" data-slide="next">
        <span class="sr-only">Next</span>
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
    </a>
</div>

Proiect.WebApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <script src="~/lib/jquery/jquery.js"></script>
    <script src="~/lib/bootstrap/js/bootstrap.js" type="text/javascript"></script>
    <link rel="stylesheet" href="~/lib/bootstrap/css/bootstrap.css" />
    <link rel="stylesheet" href="~/lib/css/mycss.css" type="text/css" />
    <script src="https://cdn.jsdelivr.net/npm/handlebars@latest/dist/handlebars.js"></script>
    <link rel="icon" href="/images/logo.png" type="image/x-icon">
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbarcustom">
            <div class="container-fluid">
                <div class="float-left">
                    <a href="/"><img id="imagineLogo" src="~/images/logo.png" /></a>
                    <label class="navitems">Medicify</label>
                </div>
                <div class="collapse d-inline-block float-right" id="navbarCollpase">
                    <ul class="navbar-nav ">
                        <li class="nav-item"><a class="nav-link navitems" asp-controller="Home" asp-action="Index">Acasă</a></li>
                        <li class="nav-item"><a class="nav-link navitems" asp-controller="Contact" asp-action="Index">Contact</a></li>
                        <partial name="_LoginPartial" />
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div>
        @RenderBody()
    </div>
    @RenderSection("Scripts", required: false)
    @RenderSection("Styles", false)
    @*<footer>
    </footer>*@
</body>
</html>

Proiect.WebApp/Views/Shared/_MedicPartial.cshtml
@model Guid

<div>
    <nav class="navbar navbar-light navbarcustom">
        <a class="navitems" asp-controller="Medic" asp-action="Profile" asp-route-idMedic="@Model"><p>PROFIL</p></a>
        <a class="navitems" asp-controller="Medic" asp-action="Appointments" asp-route-idMedic="@Model"><p>PROGRAMĂRI</p></a>
        <a class="navitems" asp-controller="Medic" asp-action="Patients" asp-route-idMedic="@Model"><p>PACIENȚI</p></a>
    </nav>
</div>

Proiect.WebApp/Views/Shared/_MedicPartialCard.cshtml
@model Medic

<div class="card-header">
   @Model.Specialization.Name
</div>
<div class="card-body">
    <div class="float-left">
        <h5 class="card-title">DR. @Model.Person.FirstName @Model.Person.LastName</h5>
        <p class="card-text">@Model.Description</p>
    </div>
    <div class="float-right">
        @if (Model.Image !=null)
        {<img class="image-card" src="data:@Model.Image.MimeType;base64,@(Convert.ToBase64String(Model.Image._Image))" alt="Image" />}
    </div>
</div>

Proiect.WebApp/Views/Shared/_MedicProfileCard.cshtml
@model MedicViewModel

<div>
    @if (Model.Image != null)
    {
        <div class="container">
            <img class="card-img-top profile-img" src="data:@Model.Image.MimeType;base64,@(Convert.ToBase64String(Model.Image._Image))" alt="Image Profil" />
            <a class="btn btn-danger" asp-action="DeleteProfilePicture" asp-controller="Medic" asp-route-idImage="@Model.IdImage" asp-route-idMedic="@Model.Id">Șterge poza de profil</a>
        </div>
    }
    <div class="card-body">
        <h5 class="card-title">@Model.FirstName @Model.LastName</h5>
        <p class="card-text">@Model.Description</p>
    </div>
    <ul class="list-group list-group-flush">
        <li class="list-group-item">Data nașterii: @Model.BirthDay</li>
        <li class="list-group-item">Telefon: @Model.PhoneNumber</li>
        <li class="list-group-item">Email: @Model.Email</li>
        <li class="list-group-item">Sex: @Model.Sex</li>
        <li class="list-group-item">Cod Identificare: @Model.IdentificationCode</li>
        <li class="list-group-item">Colegiul Medicilor: @Model.MedicalCollegeYear</li>
        @if (Model.Specialization != null)
        {
            <li class="list-group-item">Specializare: @Model.Specialization.Name</li>
        }
        <li class="list-group-item">Spital: @Model.Hospital</li>
        <li class="list-group-item">Competente: @Model.Abilities</li>
        <li class="list-group-item">Studii: @Model.Education</li>
    </ul>
</div>

Proiect.WebApp/Views/Shared/_PacientPartial.cshtml
@model Guid

<nav class="navbar navbar-light navbarcustom">
    <a class="navitems" asp-controller="Patient" asp-action="Profile" asp-route-idPatient="@Model"><p>PROFIL</p></a>
    <a class="navitems" asp-controller="Patient" asp-action="Portfolio" asp-route-idPatient="@Model"><p>DOSAR</p></a>
    <a class="navitems" asp-controller="Patient" asp-action="Medicines" asp-route-idPatient="@Model"><p>MEDICAMENTE</p></a>
    <a class="navitems" asp-controller="Patient" asp-action="Medics" asp-route-idPatient="@Model"><p>MEDICI</p></a>
    <a class="navitems" asp-controller="Patient" asp-action="Appointments" asp-route-idPatient="@Model"><p>PROGRAMĂRI</p></a>
</nav>

Proiect.WebApp/Views/Shared/_PatientProfileCard.cshtml
@model PatientViewModel

<div>
    @if (Model.Image != null)
    {
        <div class="container">
            <img class="card-img-top profile-img" src="data:@Model.Image.MimeType;base64,@(Convert.ToBase64String(Model.Image._Image))" alt="Image Profil" />
            <a class="btn btn-danger" asp-action="DeleteProfilePicture" asp-controller="Patient" asp-route-idImage="@Model.IdImage" asp-route-idPatient="@Model.Id">Șterge poza de profil</a>
        </div>
    }
    <div class="card-body">
        <h5 class="card-title">@Model.FirstName @Model.LastName</h5>
    </div>
    <ul class="list-group list-group-flush">
        <li class="list-group-item">Data nașterii: @Model.BirthDay</li>
        <li class="list-group-item">Telefon: @Model.PhoneNumber</li>
        <li class="list-group-item">Email: @Model.Email</li>
        <li class="list-group-item">Sex: @Model.Sex</li>
        <li class="list-group-item">Adresă: @Model.Address</li>
    </ul>
</div>

Proiect.WebApp/Views/Shared/_SpecializationCard.cshtml
@model Specialization

<img class="card-img-top image-specialization-card" src="data:@Model.Image.MimeType;base64,@(Convert.ToBase64String(Model.Image._Image))" alt="Image" />
<div class="card-body text-centered">
    <h5 class="card-title">@Model.Name</h5>
    <p class="card-text">@Model.Image.Description</p>
</div>